#
# SPDX-License-Identifier: Apache-2.0
#
---
- name: Deploy Opensource custom resource definitions and operator
  hosts: localhost
  vars_files:
    - /_cfg/operator-console-vars.yml
  vars:
    state: present
    wait_timeout: 3600
  roles:
    - ibm.blockchain_platform.fabric_operator_crds
