#
# SPDX-License-Identifier: Apache-2.0
#

trigger:
  - master
  - release-1.4

variables:
  FABRIC_VERSION: 2.2
  NODE_VER: 12.x
  PATH: $(Build.Repository.LocalPath)/bin:/bin:/usr/bin:/sbin:/usr/sbin:/usr/local/bin:/usr/local/sbin

jobs:
  - job: CommercialPaper_Go
    displayName: Commercial Paper (Go)
    pool:
      vmImage: ubuntu-18.04
    steps:
      - template: templates/install-deps.yml
      - template: templates/commercial-paper/azure-pipelines-go.yml

  - job: CommercialPaper_Java
    displayName: Commercial Paper (Java)
    pool:
      vmImage: ubuntu-18.04
    steps:
      - template: templates/install-deps.yml
      - template: templates/commercial-paper/azure-pipelines-java.yml

  - job: CommercialPaper_JavaScript
    displayName: Commercial Paper (JavaScript)
    pool:
      vmImage: ubuntu-18.04
    steps:
      - template: templates/install-deps.yml
      - template: templates/commercial-paper/azure-pipelines-javascript.yml

  - job: FabCar_Go
    displayName: FabCar (Go)
    pool:
      vmImage: ubuntu-18.04
    steps:
      - template: templates/install-deps.yml
      - template: templates/fabcar/azure-pipelines-go.yml

  - job: FabCar_Java
    displayName: FabCar (Java)
    pool:
      vmImage: ubuntu-18.04
    steps:
      - template: templates/install-deps.yml
      - template: templates/fabcar/azure-pipelines-java.yml

  - job: FabCar_JavaScript
    displayName: FabCar (JavaScript)
    pool:
      vmImage: ubuntu-18.04
    steps:
      - template: templates/install-deps.yml
      - template: templates/fabcar/azure-pipelines-javascript.yml

  - job: Fabcar_TypeScript
    displayName: FabCar (TypeScript)
    pool:
      vmImage: ubuntu-18.04
    steps:
      - template: templates/install-deps.yml
      - template: templates/fabcar/azure-pipelines-typescript.yml

  - job: TestNetwork
    displayName: Test Network
    pool:
      vmImage: ubuntu-18.04
    steps:
      - template: templates/install-deps.yml
      - template: templates/test-network/azure-pipelines.yml
