#
# SPDX-License-Identifier: Apache-2.0
#
name: Test Network Events ðŸ’¡
run-name: ${{ github.actor }} is running the Test Network Events tests ðŸ’¡

on:
  workflow_dispatch:
  push:
    branches: [ "main", "release-2.5" ]
  pull_request:
    branches: [ "main", "release-2.5" ]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  events:
    runs-on: ${{ github.repository == 'hyperledger/fabric-samples' && 'fabric-ubuntu-22.04' || 'ubuntu-22.04' }}
    strategy:
      matrix:
        chaincode-language:
          - go
          - javascript
          - java
        chaincode-name:
          - events
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up the test network runtime
        uses: ./.github/actions/test-network-setup

      - name: Run Test
        working-directory: test-network
        run: ../ci/scripts/run-test-network-events.sh
        env:
          CHAINCODE_NAME: ${{ matrix.chaincode-name }}
          CHAINCODE_LANGUAGE: ${{ matrix.chaincode-language }}
