name: Full Stack AppDev E2E Test
run-name: ${{ github.actor }} is running the FSAT E2E Test ğŸš€

on:
  workflow_dispatch:
  pull_request:
    branches:
    - "main"
    paths:
    - "full-stack-asset-transfer-guide/**"

env:
  GO_VER: 1.18.3
  NODE_VER: 16.x
  K9S_VERSION: v0.25.3
  JUST_VERSION: 1.2.0

jobs:
  appdev:
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v3

    - uses: actions/setup-go@v3
      with:
        go-version: ${{ env.GO_VER }}

    - uses: actions/setup-node@v3
      with:
        node-version: ${{ env.NODE_VER }}

    - name: Install k9s
      run: |
        curl --fail --silent --show-error -L https://github.com/derailed/k9s/releases/download/${K9S_VERSION}/k9s_Linux_x86_64.tar.gz -o /tmp/k9s_Linux_x86_64.tar.gz
        tar -zxf /tmp/k9s_Linux_x86_64.tar.gz -C /usr/local/bin k9s
        sudo chown root /usr/local/bin/k9s
        sudo chmod 755 /usr/local/bin/k9s

    - name: Install just
      run: |
        curl --proto '=https' --tlsv1.2 -sSf https://just.systems/install.sh | bash -s -- --tag ${JUST_VERSION} --to /usr/local/bin

    - name: Install weft
      run: |
        npm install -g @hyperledger-labs/weft

    - name: Install fabric CLI
      working-directory: full-stack-asset-transfer-guide
      run: |
        curl -sSL https://raw.githubusercontent.com/hyperledger/fabric/main/scripts/install-fabric.sh | bash -s -- binary
        echo ${PWD}/bin >> $GITHUB_PATH

    - name: just test-appdev
      working-directory: full-stack-asset-transfer-guide
      run: just test-appdev

    - run: echo "ğŸ This job's status is ${{ job.status }}."
