#
# SPDX-License-Identifier: Apache-2.0
#
name: Test Network HSM ðŸ
run-name: ${{ github.actor }} is running the Test Network HSM tests ðŸ

on:
  workflow_dispatch:
  push:
    branches: [ "main", "release-2.5" ]
  pull_request:
    branches: [ "main", "release-2.5" ]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  hsm:
    runs-on: ${{ github.repository == 'hyperledger/fabric-samples' && 'fabric-ubuntu-22.04' || 'ubuntu-22.04' }}
    strategy:
      matrix:
        chaincode-language:
          - go
          - javascript
          - typescript
          - java
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up the test network runtime
        uses: ./.github/actions/test-network-setup

      - name: Install SoftHSM
        run: sudo apt install -y softhsm2

      - name: Set up SoftHSM
        env:
          TMPDIR: ${{ runner.temp }}
          SOFTHSM2_CONF: ${{ github.workspace }}/softhsm2.conf
        run: |
          echo "directories.tokendir = ${TMPDIR}" > "${SOFTHSM2_CONF}"
          softhsm2-util --init-token --slot 0 --label "ForFabric" --pin 98765432 --so-pin 1234

      - name: Run Test Network HSM
        working-directory: test-network
        env:
          CHAINCODE_LANGUAGE: ${{ matrix.chaincode-language }}
          SOFTHSM2_CONF: ${{ github.workspace }}/softhsm2.conf
        run: ../ci/scripts/run-test-network-hsm.sh
