#
# SPDX-License-Identifier: Apache-2.0
#
name: Test Network BFT Orderer üçü
run-name: ${{ github.actor }} is running the Test Network with BFT Orderer tests üçü

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  basic:
    runs-on: ${{ github.repository == 'hyperledger/fabric-samples' && 'fabric-ubuntu-22.04' || 'ubuntu-22.04' }}
    strategy:
      matrix:
        chaincode-language:
          - go
          - javascript
          - typescript
          - java
        crypto:
          - cryptogen
          - ca

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up the test network runtime
        uses: ./.github/actions/test-network-setup
        # Note: The default Fabric version for CI is currently the latest LTS (v2.5.x).
        # To test BFT Orderers, Fabric v3.x is explicitly specified here.
        with:
          fabric-version: 3.1.1

      - name: Run Test Network with BFT Orderers
        working-directory: test-network
        run: ../ci/scripts/run-test-network-basic.sh
        env:
          CHAINCODE_LANGUAGE: ${{ matrix.chaincode-language }}
          ORDERER_TYPE: bft
          CRYPTO: ${{ matrix.crypto }}
