#
# SPDX-License-Identifier: Apache-2.0
#
name: Test Network Gateway üñ•Ô∏è
run-name: ${{ github.actor }} is running the Test Network Gateway tests üñ•Ô∏è

on:
  workflow_dispatch:
  push:
    branches: [ "main", "release-2.5" ]
  pull_request:
    branches: [ "main", "release-2.5" ]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  gateway:
    runs-on: fabric-ubuntu-20.04
    strategy:
      matrix:
        chaincode-language:
          - go
          - javascript
          - typescript
          - java
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up the test network runtime
        uses: ./.github/actions/test-network-setup

      - name: Run Test
        working-directory: test-network
        env:
          CHAINCODE_LANGUAGE: ${{ matrix.chaincode-language }}
        run: ../ci/scripts/run-test-network-gateway.sh
