#
# SPDX-License-Identifier: Apache-2.0
#
name: Test Network Secured ðŸ””
run-name: ${{ github.actor }} is running the Test Network Secured tests ðŸ””

on:
  workflow_dispatch:
  push:
    branches: [ "main", "release-2.5" ]
  pull_request:
    branches: [ "main", "release-2.5" ]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  secured:
    runs-on: fabric-ubuntu-20.04
    strategy:
      matrix:
        chaincode-language:
          - go
        chaincode-name:
          - secured
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up the test network runtime
        uses: ./.github/actions/test-network-setup

      - name: Run Test
        working-directory: test-network
        run: ../ci/scripts/run-test-network-secured.sh
        env:
          CHAINCODE_NAME: ${{ matrix.chaincode-name }}
          CHAINCODE_LANGUAGE: ${{ matrix.chaincode-language }}
