#
# SPDX-License-Identifier: Apache-2.0
#
name: Kubernetes Test Network üçí
run-name: ${{ github.actor }} is testing the Kubernetes Test Network üçí

on:
  workflow_dispatch:
  push:
    branches: [ "main", "release-2.5" ]
  pull_request:
    branches: [ "main", "release-2.5" ]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  ccaas-java:
    runs-on: ${{ github.repository == 'hyperledger/fabric-samples' && 'fabric-ubuntu-22.04' || 'ubuntu-22.04' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Test the network
        working-directory: test-network-k8s
        run: ../ci/scripts/run-k8s-test-network-basic.sh
        env:
          CLIENT_LANGUAGE: typescript
          CHAINCODE_LANGUAGE: java

  ccaas-external:
    runs-on: ${{ github.repository == 'hyperledger/fabric-samples' && 'fabric-ubuntu-22.04' || 'ubuntu-22.04' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Test the network
        working-directory: test-network-k8s
        run: ../ci/scripts/run-k8s-test-network-basic.sh
        env:
          CLIENT_LANGUAGE: typescript
          CHAINCODE_LANGUAGE: external

  k8s-builder:
    runs-on: ${{ github.repository == 'hyperledger/fabric-samples' && 'fabric-ubuntu-22.04' || 'ubuntu-22.04' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Test the network
        working-directory: test-network-k8s
        run: ../ci/scripts/run-k8s-test-network-basic.sh
        env:
          CHAINCODE_NAME: basic
          CHAINCODE_LANGUAGE: java
          CHAINCODE_BUILDER: k8s

  multi-namespace:
    runs-on: ${{ github.repository == 'hyperledger/fabric-samples' && 'fabric-ubuntu-22.04' || 'ubuntu-22.04' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Test the network
        working-directory: test-network-k8s
        run: ../ci/scripts/run-k8s-test-network-basic.sh
        env:
          ORG0_NS: org0-namespace
          ORG1_NS: org1-namespace
          ORG2_NS: org2-namespace
          CHAINCODE_NAME: basic
          CHAINCODE_LANGUAGE: java
          CHAINCODE_BUILDER: k8s

  bft-orderer:
    runs-on: ${{ github.repository == 'hyperledger/fabric-samples' && 'fabric-ubuntu-22.04' || 'ubuntu-22.04' }}
    # This job requires Fabric v3.0 or later, which is only supported on 'main'.
    # Ensure it does not run on 'release-2.5' or earlier versions.
    if: ${{ github.ref == 'refs/heads/main' || github.event.pull_request.base.ref == 'main' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Test the network
        working-directory: test-network-k8s
        run: ../ci/scripts/run-k8s-test-network-basic.sh
        env:
          CLIENT_LANGUAGE: typescript
          CHAINCODE_LANGUAGE: java
          # Note: The default Fabric version for CI is currently the latest LTS (v2.5.x).
          # To test BFT Orderers, Fabric v3.x is explicitly specified here.
          FABRIC_VERSION: '3.1'
          ORDERER_TYPE: bft
