name: Full Stack Asset Transfer Guide ðŸš€
run-name: ${{ github.actor }} is testing the Full Stack Asset Transfer Guide ðŸš€

on:
  workflow_dispatch:
  pull_request:
    branches:
      - "main"
      - "release-2.5"

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  ansible:
    runs-on: ${{ github.repository == 'hyperledger/fabric-samples' && 'fabric-ubuntu-22.04' || 'ubuntu-22.04' }}
    steps:
      - uses: actions/checkout@v4
      - name: Set up Full Stack Runtime
        uses: ./.github/actions/fsat-setup
      - run: just test-ansible
        working-directory: full-stack-asset-transfer-guide

  appdev:
    runs-on: ${{ github.repository == 'hyperledger/fabric-samples' && 'fabric-ubuntu-22.04' || 'ubuntu-22.04' }}
    steps:
      - uses: actions/checkout@v4
      - name: Set up Full Stack Runtime
        uses: ./.github/actions/fsat-setup
      - run: just test-appdev
        working-directory: full-stack-asset-transfer-guide

  chaincode:
    runs-on: ${{ github.repository == 'hyperledger/fabric-samples' && 'fabric-ubuntu-22.04' || 'ubuntu-22.04' }}
    steps:
      - uses: actions/checkout@v4
      - name: Set up Full Stack Runtime
        uses: ./.github/actions/fsat-setup
      - run: just test-chaincode
        working-directory: full-stack-asset-transfer-guide

  cloud:
    runs-on: ${{ github.repository == 'hyperledger/fabric-samples' && 'fabric-ubuntu-22.04' || 'ubuntu-22.04' }}
    steps:
      - uses: actions/checkout@v4
      - name: Set up Full Stack Runtime
        uses: ./.github/actions/fsat-setup
      - run: just test-cloud
        working-directory: full-stack-asset-transfer-guide

  console:
    runs-on: ${{ github.repository == 'hyperledger/fabric-samples' && 'fabric-ubuntu-22.04' || 'ubuntu-22.04' }}
    steps:
      - uses: actions/checkout@v4
      - name: Set up Full Stack Runtime
        uses: ./.github/actions/fsat-setup
      - run: just test-console
        working-directory: full-stack-asset-transfer-guide
